from django.urls import path
from . import views

urlpatterns = [
    path('api/login.json', views.login),
    path('projectInterController/projectList.json', views.projectList),
    path('api/getDictList.json', views.getDictList),
    path('taskInterController/taskList.json', views.taskList),
    path('engineroomInterController/queryEngineroomInfo.json', views.queryEngineroomInfo),
    path('engineroomInterController/updateEngineroomInfo.json', views.updateEngineroomInfo),
    path('geospatialInterController/geospatialList.json', views.geospatialList),
    path('rackinfoInterController/rackList.json', views.rackList),
    path('rackinfoInterController/addRackInfo.json', views.addRackInfo),
    path('rackinfoInterController/updateRackInfo.json', views.updateRackInfo),
    path('rackinfoInterController/deleteRackInfo.json', views.deleteRackInfo),
    path('facilityInterController/queryFacility.json', views.queryFacility),
    path('facilityInterController/addFacility.json', views.addFacility),
    path('facilityInterController/updateFacility.json', views.updateFacility),
    path('facilityInterController/deleteFacility.json', views.deleteFacility),
    path('airConditioningInterController/queryAirConditioning.json', views.queryAirConditioning),
    path('airConditioningInterController/addAirConditioning.json', views.addAirConditioning),
    path('airConditioningInterController/updateAirConditioning.json', views.updateAirConditioning),
    path('airConditioningInterController/deleteAirConditioning.json', views.deleteAirConditioning),
    path('airOutDoorinterController/queryAirOutDoor.json', views.queryAirOutDoor),
    path('airOutDoorinterController/addAirOutDoor.json', views.addAirOutDoor),
    path('airOutDoorinterController/updateAirOutDoor.json', views.updateAirOutDoor),
    path('airOutDoorinterController/deleteAirOutDoor.json', views.deleteAirOutDoor),
    path('distributorsInterController/queryDistributors.json', views.queryDistributors),
    path('distributorsInterController/addDistributors.json', views.addDistributors),
    path('distributorsInterController/updateDistributors.json', views.updateDistributors),
    path('distributorsInterController/deleteDistributors.json', views.deleteDistributors),
    path('rectifierInterController/queryRectifier.json', views.queryRectifier),
    path('rectifierInterController/addRectifier.json', views.addRectifier),
    path('rectifierInterController/updateRectifier.json', views.updateRectifier),
    path('rectifierInterController/deleteRectifier.json', views.deleteRectifier),
    path('upsInterController/queryUps.json', views.queryUps),
    path('upsInterController/updateUps.json', views.updateUps),
    path('upsInterController/addUps.json', views.addUps),
    path('upsInterController/deleteUps.json', views.deleteUps),
    path('batteryInterController/queryBattery.json', views.queryBattery),
    path('batteryInterController/addBattery.json', views.addBattery),
    path('batteryInterController/updateBattery.json', views.updateBattery),
    path('batteryInterController/deleteBattery.json', views.deleteBattery),
    path('colheadcabinetinterController/queryColheadcabinet.json', views.queryColheadcabinet),
    path('colheadcabinetinterController/addColheadcabinet.json', views.addColheadcabinet),
    path('colheadcabinetinterController/updateColheadcabinet.json', views.updateColheadcabinet),
    path('colheadcabinetinterController/deleteColheadcabinet.json', views.deleteColheadcabinet),
    path('facilityPlotInterController/queryFacilityPlot.json', views.queryFacilityPlot),
    path('facilityPlotInterController/addFacilityPlot.json', views.addFacilityPlot),
    path('facilityPlotInterController/updateFacilityPlot.json', views.updateFacilityPlot),
    path('facilityPlotInterController/deleteFacilityPlot.json', views.deleteFacilityPlot),
    path('maccolInterController/queryMaccolInfo.json', views.queryMaccolInfo),
    path('maccolInterController/updateMaccolInfo.json', views.updateMaccolInfo),
    path('maccolInterController/addMaccolInfo.json', views.addMaccolInfo),
    path('maccolInterController/deleteMaccolInfo.json', views.deleteMaccolInfo),
    
]